### ISSUE TITLE
Unable to composer install

### ISSUE THREAD

**Issue by neuronet77** [wdmg/butterfly.cms#3]
Problem 1
    - Installation request for codeception/verify 0.5.0 -> satisfiable by codeception/verify[0.5.0].
    - codeception/verify 0.5.0 requires php 5.6.* -> your PHP version (8.0.11) does not satisfy that requirement.
  Problem 2
    - Installation request for doctrine/instantiator 1.0.5 -> satisfiable by doctrine/instantiator[1.0.5].
    - doctrine/instantiator 1.0.5 requires php >=5.3,<8.0-DEV -> your PHP version (8.0.11) does not satisfy that requirement.
  Problem 3
    - Installation request for fakerphp/faker v1.9.2 -> satisfiable by fakerphp/faker[v1.9.2].
    - fakerphp/faker v1.9.2 requires php ^5.3.3 || ^7.0 -> your PHP version (8.0.11) does not satisfy that requirement.
  Problem 4
    - Installation request for myclabs/deep-copy 1.7.0 -> satisfiable by myclabs/deep-copy[1.7.0].
    - myclabs/deep-copy 1.7.0 requires php ^5.6 || ^7.0 -> your PHP version (8.0.11) does not satisfy that requirement.
  Problem 5
    - Installation request for phpdocumentor/reflection-docblock 3.3.2 -> satisfiable by phpdocumentor/reflection-docblock[3.3.2].
    - phpdocumentor/reflection-docblock 3.3.2 requires php ^5.6 || ^7.0 -> your PHP version (8.0.11) does not satisfy that requirement.
  Problem 6
    - Installation request for phpdocumentor/type-resolver 0.4.0 -> satisfiable by phpdocumentor/type-resolver[0.4.0].
    - phpdocumentor/type-resolver 0.4.0 requires php ^5.5 || ^7.0 -> your PHP version (8.0.11) does not satisfy that requirement.
  Problem 7
    - Installation request for phpspec/prophecy v1.10.3 -> satisfiable by phpspec/prophecy[v1.10.3].
    - phpspec/prophecy v1.10.3 requires php ^5.3|^7.0 -> your PHP version (8.0.11) does not satisfy that requirement.
  Problem 8
    - Installation request for phpunit/php-code-coverage 4.0.8 -> satisfiable by phpunit/php-code-coverage[4.0.8].
    - phpunit/php-code-coverage 4.0.8 requires php ^5.6 || ^7.0 -> your PHP version (8.0.11) does not satisfy that requirement.
  Problem 9
    - Installation request for phpunit/php-timer 1.0.9 -> satisfiable by phpunit/php-timer[1.0.9].
    - phpunit/php-timer 1.0.9 requires php ^5.3.3 || ^7.0 -> your PHP version (8.0.11) does not satisfy that requirement.
  Problem 10
    - Installation request for phpunit/phpunit 5.7.27 -> satisfiable by phpunit/phpunit[5.7.27].
    - phpunit/phpunit 5.7.27 requires php ^5.6 || ^7.0 -> your PHP version (8.0.11) does not satisfy that requirement.
  Problem 11
    - Installation request for phpunit/phpunit-mock-objects 3.4.4 -> satisfiable by phpunit/phpunit-mock-objects[3.4.4].
    - phpunit/phpunit-mock-objects 3.4.4 requires php ^5.6 || ^7.0 -> your PHP version (8.0.11) does not satisfy that requirement.
  Problem 12
    - Installation request for sebastian/diff 1.4.3 -> satisfiable by sebastian/diff[1.4.3].
    - sebastian/diff 1.4.3 requires php ^5.3.3 || ^7.0 -> your PHP version (8.0.11) does not satisfy that requirement.
  Problem 13
    - Installation request for sebastian/environment 2.0.0 -> satisfiable by sebastian/environment[2.0.0].
    - sebastian/environment 2.0.0 requires php ^5.6 || ^7.0 -> your PHP version (8.0.11) does not satisfy that requirement.
  Problem 14
    - phpunit/php-code-coverage 4.0.8 requires php ^5.6 || ^7.0 -> your PHP version (8.0.11) does not satisfy that requirement.
    - codeception/phpunit-wrapper 6.0.21 requires phpunit/php-code-coverage >=4.0.4 <6.0 -> satisfiable by phpunit/php-code-coverage[4.0.8].
    - Installation request for codeception/phpunit-wrapper 6.0.21 -> satisfiable by codeception/phpunit-wrapper[6.0.21].

**Comment by alex-wdmg** [comment]
Not confirmed. You seem to be using PHP version 8, which is supported in Yii 2.0.45. (use version 2.0.40 / 2.0.42.1 as the most stable package for required PHP 5.6  or 7.*

In addition, please note that the errors are third-party software, not the wdmg/* vendor. Apparently their code is not yet ready to support the latest PHP version. 

You can solve the problem by downgrading PHP CLI.

See more [https://www.yiiframework.com/news/443/yii-2-0-45](url)
